name: notes_firebase_ddd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dartz for Either-type
  # freezed_annotation for union
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1 
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  google_sign_in: ^5.0.7
  lint: ^1.8.2
  get_it: ^7.2.0
  another_flushbar: ^1.10.28
  uuid: ^3.0.5
  auto_route: ^3.2.3+1
  kt_dart: ^0.10.0
  json_annotation: ^4.4.0
  
  

dev_dependencies:
  build_runner:
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
